### ISSUE TITLE
ASHRAE2006 and Guideline36 fails to simulate with directional derivatives

### ISSUE THREAD

**Issue by chria** [NREL/SOEP-QSS-Test#21] opened 2022-05-31 13:35 UTC
PyFMI simulation of ASHRAE2006 & Guideline36 fails when directional derivatives are turned on:

ASHRAE2006
Warning: Possible chattering detected at t = 1.308000e+04 in state event(s): [57 59 61 63 65]
Simulation failed:  'The right-hand side function had repeated recoverable errors. At time 39240.000000.

Guideline36
"Simulation failed: 'The right-hand side function had repeated recoverable errors. At time 39120.000000.'"

**Comment by modelonrobinandersson** [comment] 2022-08-16 16:32
This seems to caused by two issues that are resolved in the next version of OCT:

1. zeroDerivatives were not picked up correctly, which was used by the function Buildings.Fluid.BaseClasses.FlowModels.basicFlowFunction_dp, which in turn propagated further down.
2. We have now improved how the directional derivative is calculated for expressions such as `x^y` when x approaches `0` and `y>1`.

**Comment by DeadParrot** [comment] 2022-08-18 02:29
Both models' PyFMI (CVode) runs complete with FMUs built with directional derivative support using OCT dev build OCT-dev-cw-5212-18478f3488ff1272c52222a29d72215983eadeec.

Both models still give "Possible chattering" warnings but if that proves to indicate model problems that affect QSS a separate Issue will be opened.

**Closed as completed by DeadParrot** 2022-08-18 02:29 UTC
Labels: OCT

**Comment by DeadParrot** [comment] 2022-10-11 07:26
Thanks, Robin. I will see how these 2 models run now.

I need to understand more about how derivative annotations affect the
generated FMU and QSS. Specifically, can someone describe:

   - Whether QSS would need to look at XML annotations to get this
   information or are these made into der(...) variables in the FMU?
   - Is this a mechanism for getting derivatives of input and/or event
   indicators into QSS and do we need to add support for that?
   - Can it also be used to provide higher order derivatives for state
   variables and would that be different than just providing an explicit
   der(der(...)) variable?

If we eventually need to support this I guess I need to know if we need to
do anything on the QSS side for models like these that use derivative
annotations.

Regards,
Stuart
-- 
Stuart Mentzer
Objexx Engineering
objexx.com
+1 781 455 1150
